(require 'smartrep)
(declare-function smartrep-define-key "smartrep")
(global-set-key (kbd "C-M-c") 'mc/edit-lines)
(global-set-key (kbd "C-*")   'mc/mark-all-like-this)
(global-unset-key "\C-t")
(smartrep-define-key global-map "C-t"
  '(("C-p"      . 'mc/mark-previous-like-this)
    ("C-n"      . 'mc/mark-next-like-this)
    ("C-P"      . 'mc/mark-previous-word-like-this)
    ("C-N"      . 'mc/mark-next-word-like-this)
    ("M-p"      . 'mc/mark-previous-symbol-like-this)
    ("M-n"      . 'mc/mark-next-symbol-like-this)
    ("*"        . 'mc/mark-all-like-this)))
